Deprecation of MultiMC/manual vanilla install on CurseForge
Fabulously-Optimized/wiki pull request #79
Opened 2023-04-16 11:45 UTC by Madis0

https://github.com/Fabulously-Optimized/fabulously-optimized/issues/627

2023-04-16 13:39 UTC, Madis0 commented on install-instructions.md
> +TODO
TODO

2023-11-11 22:43 UTC, Madis0 commented on install-instructions.md
> -For macOS or Linux [you need Java](https://adoptium.net/) to run the Fabric Installer.
Bring that part back through mrpack-to-zip tooö

2024-02-12 16:54 UTC, Madis0 commented on install-instructions.md
> +1. Download [vanilla installer](https://download.fo/vanilla) and run it
todo: windows, macos, linux quirks that will appear on running it

2024-02-12 17:49 UTC, Imzxhir requested changes

2024-02-12 17:49 UTC, Imzxhir commented on install-instructions.md
> +    * Linux:
```suggestion
    * macOS: Open the .dmg file, double click the 'Fabulously Optimized Installer' and click 'Open' when asked in a prompt.
```

2024-04-02 09:38 UTC, vgskye commented on install-instructions.md
> +Note: you may now see a new file _paigaldaja_meta.json_ next to the installer. This is a configuration file that ensures smoother upgrades and remembers some of your install settings.
this is technically incorrect here; `paigaldaja_meta.json` is saved in the profile dir

2024-10-20 13:30 UTC, merged